apiVersion: v1
kind: Service
metadata:
  name: secure-file-service
  namespace: secure-file-platform
spec:
  selector:
    app: secure-file
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
