apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-file-app
  namespace: secure-file-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-file
  template:
    metadata:
      labels:
        app: secure-file
    spec:
      containers:
      - name: secure-file-container
        image: meghgohil/secure-file-platform:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AWS_REGION
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_BUCKET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
